### PR TITLE
Remove token from isolator API

### PR DESCRIPTION
**Pull request by nqn**

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
Could you also remove token usage in the isolator? See https://github.com/intelsdi-x/kubernetes/blob/5b91fc572bca9141182b6741559c1124d85a5289/cluster/addons/iso-client/coreaffinity/eventdispatcher_client.go#L60

**Comment by ConnorDoyle** [comment]
Hey, `ext-iso` was just updated to fix up the squash problem. If rebasing is troublesome, do you mind checking out that branch and cherry-picking your commit on top in a new PR? Sorry for the hassle & thanks.

**Comment by flyingcougar** [comment]
@nqn I can finish this if you are busy.

**Comment by ConnorDoyle** [comment]
@flyingcougar if you have time to prep a new PR with the commit please do. Thanks!

**Comment by flyingcougar** [comment]
addressed in PR #36

**Pull request closed without merging**
